#!/usr/bin/env bash
# ============================================================
# RAPIDA Crisis Mapping — Linux/Mac Setup Script
# Run once after cloning: chmod +x setup.sh && ./setup.sh
# ============================================================
set -e

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

echo -e "${CYAN}"
echo "  ██████╗  █████╗ ██████╗ ██╗██████╗  █████╗ "
echo "  ██╔══██╗██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗"
echo "  ██████╔╝███████║██████╔╝██║██║  ██║███████║"
echo "  ██╔══██╗██╔══██║██╔═══╝ ██║██║  ██║██╔══██║"
echo "  ██║  ██║██║  ██║██║     ██║██████╔╝██║  ██║"
echo "  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝"
echo -e "${NC}"
echo -e "${CYAN}  UNDP Crisis Mapping Platform — Setup${NC}"
echo "  ──────────────────────────────────────────"
echo ""

# ── Prerequisites check ────────────────────────────────────
echo -e "${YELLOW}[1/5] Checking prerequisites...${NC}"

if ! command -v docker &>/dev/null; then
  echo -e "${RED}✗ Docker not found. Install from https://docs.docker.com/get-docker/${NC}"; exit 1
fi
echo -e "  ${GREEN}✓ Docker $(docker --version | awk '{print $3}' | tr -d ',')${NC}"

if ! docker info &>/dev/null; then
  echo -e "${RED}✗ Docker daemon is not running. Start Docker Desktop or run: sudo systemctl start docker${NC}"; exit 1
fi
echo -e "  ${GREEN}✓ Docker daemon running${NC}"

if ! command -v node &>/dev/null; then
  echo -e "${RED}✗ Node.js not found. Install v18+ from https://nodejs.org/${NC}"; exit 1
fi
NODE_VER=$(node -e "process.stdout.write(process.version)")
echo -e "  ${GREEN}✓ Node.js $NODE_VER${NC}"

if ! command -v npm &>/dev/null; then
  echo -e "${RED}✗ npm not found.${NC}"; exit 1
fi
echo -e "  ${GREEN}✓ npm $(npm --version)${NC}"

# ── Create .env ────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[2/5] Creating environment file...${NC}"

cat > .env << 'ENVEOF'
# ============================================================
# RAPIDA — Environment Variables (auto-generated by setup.sh)
# ============================================================

POSTGRES_USER=crisis_user
POSTGRES_PASSWORD=changeme
POSTGRES_DB=crisis_mapper
DATABASE_URL=postgresql://crisis_user:changeme@postgres:5432/crisis_mapper

MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
MINIO_BUCKET=crisis-reports
MINIO_USE_SSL=false
MINIO_PUBLIC_URL=http://localhost:9000

GROQ_API_KEY=YOUR_GROQ_API_KEY

NODE_ENV=development
PORT=3001
DASHBOARD_API_KEY=rapida-dev-key-2026
CORS_ORIGINS=http://localhost:5173,http://localhost:8080

VITE_API_BASE_URL=/api/v1
VITE_DASHBOARD_KEY=rapida-dev-key-2026
VITE_ENABLE_AI=true
ENVEOF

echo -e "  ${GREEN}✓ .env created${NC}"

# ── Install dependencies ───────────────────────────────────
echo ""
echo -e "${YELLOW}[3/5] Installing dependencies...${NC}"

echo -e "  Installing backend packages..."
cd backend && npm install --silent && cd ..
echo -e "  ${GREEN}✓ Backend dependencies installed${NC}"

echo -e "  Installing frontend packages..."
cd frontend && npm install --silent && cd ..
echo -e "  ${GREEN}✓ Frontend dependencies installed${NC}"

# ── Start Docker services ──────────────────────────────────
echo ""
echo -e "${YELLOW}[4/5] Starting Docker services...${NC}"

docker compose up -d postgres minio
echo -e "  ${GREEN}✓ PostgreSQL + MinIO starting...${NC}"

echo -n "  Waiting for database to be ready"
for i in $(seq 1 30); do
  if docker compose exec -T postgres pg_isready -U crisis_user -q 2>/dev/null; then
    echo -e " ${GREEN}✓${NC}"
    break
  fi
  echo -n "."
  sleep 2
  if [ $i -eq 30 ]; then
    echo -e " ${RED}✗ Timed out waiting for database${NC}"; exit 1
  fi
done

echo -e "  ${GREEN}✓ Database ready${NC}"

# ── Build frontend ─────────────────────────────────────────
echo ""
echo -e "${YELLOW}[5/5] Building frontend...${NC}"
cd frontend && npm run build --silent && cd ..
echo -e "  ${GREEN}✓ Frontend built${NC}"

# ── Done ───────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅  Setup complete!${NC}"
echo -e "${GREEN}══════════════════════════════════════════${NC}"
echo ""
echo -e "  Start the full stack with Docker:"
echo -e "  ${CYAN}docker compose up -d${NC}"
echo ""
echo -e "  Or start in dev mode (hot reload):"
echo -e "  ${CYAN}./start-dev.sh${NC}"
echo ""
echo -e "  App URL:       ${CYAN}http://localhost:5173${NC}"
echo -e "  Dashboard key: ${CYAN}rapida-dev-key-2026${NC}"
echo -e "  MinIO console: ${CYAN}http://localhost:9001${NC}  (minioadmin / minioadmin)"
echo ""
