# ============================================================
# RAPIDA Crisis Mapping — Windows Setup Script
# Run once after cloning:
#   Right-click PowerShell -> "Run as Administrator"
#   Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
#   .\setup.ps1
# ============================================================

$ErrorActionPreference = "Stop"

function Write-Step($n, $msg) { Write-Host "`n[$n/5] $msg" -ForegroundColor Yellow }
function Write-Ok($msg)       { Write-Host "  v $msg" -ForegroundColor Green }
function Write-Fail($msg)     { Write-Host "  x $msg" -ForegroundColor Red; exit 1 }

Write-Host @"

  ██████╗  █████╗ ██████╗ ██╗██████╗  █████╗
  ██╔══██╗██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗
  ██████╔╝███████║██████╔╝██║██║  ██║███████║
  ██╔══██╗██╔══██║██╔═══╝ ██║██║  ██║██╔══██║
  ██║  ██║██║  ██║██║     ██║██████╔╝██║  ██║
  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

  UNDP Crisis Mapping Platform - Windows Setup
  ─────────────────────────────────────────────
"@ -ForegroundColor Cyan

# ── Prerequisites ──────────────────────────────────────────
Write-Step 1 "Checking prerequisites..."

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Fail "Docker not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop/"
}
Write-Ok "Docker found: $(docker --version)"

try { docker info | Out-Null }
catch { Write-Fail "Docker daemon is not running. Please start Docker Desktop." }
Write-Ok "Docker daemon running"

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Fail "Node.js not found. Install v18+ from https://nodejs.org/"
}
Write-Ok "Node.js found: $(node --version)"

if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
    Write-Fail "npm not found."
}
Write-Ok "npm found: $(npm --version)"

# ── Create .env ────────────────────────────────────────────
Write-Step 2 "Creating environment file..."

$envContent = @"
# ============================================================
# RAPIDA - Environment Variables (auto-generated by setup.ps1)
# ============================================================

POSTGRES_USER=crisis_user
POSTGRES_PASSWORD=changeme
POSTGRES_DB=crisis_mapper
DATABASE_URL=postgresql://crisis_user:changeme@postgres:5432/crisis_mapper

MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
MINIO_BUCKET=crisis-reports
MINIO_USE_SSL=false
MINIO_PUBLIC_URL=http://localhost:9000

GROQ_API_KEY=YOUR_GROQ_API_KEY

NODE_ENV=development
PORT=3001
DASHBOARD_API_KEY=rapida-dev-key-2026
CORS_ORIGINS=http://localhost:5173,http://localhost:8080

VITE_API_BASE_URL=/api/v1
VITE_DASHBOARD_KEY=rapida-dev-key-2026
VITE_ENABLE_AI=true
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8 -NoNewline
Write-Ok ".env created"

# ── Install dependencies ───────────────────────────────────
Write-Step 3 "Installing dependencies..."

Write-Host "  Installing backend packages..." -ForegroundColor Gray
Set-Location backend
npm install --silent
Set-Location ..
Write-Ok "Backend dependencies installed"

Write-Host "  Installing frontend packages..." -ForegroundColor Gray
Set-Location frontend
npm install --silent
Set-Location ..
Write-Ok "Frontend dependencies installed"

# ── Start Docker services ──────────────────────────────────
Write-Step 4 "Starting Docker services..."

docker compose up -d postgres minio
Write-Ok "PostgreSQL + MinIO starting..."

Write-Host "  Waiting for database to be ready" -NoNewline -ForegroundColor Gray
$ready = $false
for ($i = 0; $i -lt 30; $i++) {
    $result = docker compose exec -T postgres pg_isready -U crisis_user -q 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host " OK" -ForegroundColor Green
        $ready = $true
        break
    }
    Write-Host "." -NoNewline
    Start-Sleep -Seconds 2
}
if (-not $ready) { Write-Fail "Timed out waiting for database" }
Write-Ok "Database ready"

# ── Build frontend ─────────────────────────────────────────
Write-Step 5 "Building frontend..."

Set-Location frontend
npm run build --silent
Set-Location ..
Write-Ok "Frontend built"

# ── Done ───────────────────────────────────────────────────
Write-Host "`n========================================" -ForegroundColor Green
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Start the full stack with Docker:" -ForegroundColor White
Write-Host "  docker compose up -d" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Or start in dev mode (hot reload):" -ForegroundColor White
Write-Host "  .\start-dev.ps1" -ForegroundColor Cyan
Write-Host ""
Write-Host "  App URL:       http://localhost:5173" -ForegroundColor Cyan
Write-Host "  Dashboard key: rapida-dev-key-2026" -ForegroundColor Cyan
Write-Host "  MinIO console: http://localhost:9001  (minioadmin / minioadmin)" -ForegroundColor Cyan
Write-Host ""
